<?php if( ! defined('BASEPATH')) exit('No direct script access allowed');

class Excel {

	public function __construct($class = NULL)
	{

		

// autoload.php @generated by Composer

    require_once __DIR__ . '/composer/autoload_real.php';

    return ComposerAutoloaderInitd305bdb165b88151e8238158490a9c09::getLoader();

		
	}

	
}
